name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Install dependencies
      run: |
        npm install
        lein deps
    - name: Check formatting
      run: lein cljfmt check
    - name: Run tests clj
      run: |
        lein test
    - name: Run tests cljs
      run: |
        lein test-js
    - name: Release
      env:
        RELEASE_USERNAME: ${{ secrets.ReleaseUsername }}
        RELEASE_PASSWORD: ${{ secrets.ReleasePassword }}
      run: |
        git config --global user.email "ci@pinkgorilla.org"
        git config --global user.name "CI/CD"
        lein release